### ISSUE TITLE
TODO: Perceptron

### ISSUE THREAD

**Issue by david111esc** [david111esc/MachineLearning#1]
- [ ] Perceptron Algorithm
- [ ] 印出 Data set and decision boundery
- [ ] 印出 Perceptron Object function 
- [ ] Perceptron 在 Full Gradient 之下的 Objective function
- [ ] 印出 Gradient 路徑
- [ ] 印出 Stochastic Gradient 路徑
- [ ] 切線泰勒近似函數
- [ ] 二次泰勒近似函數
